#!/usr/bin/env ruby

require 'optparse'
require 'norikra/querydump/format'

def usage(code)
  warn "Usage: norikra-querydump-format -i (text|json) [inputfile]"
  exit code
end

params = ARGV.getopts('hi:')
if params['h']
  usage(0)
end

case ARGV.size
when 0
  src = STDIN
when 1
  src = File.open(ARGV.first)
else
  usage(1)
end

case params['i']
when 'text'
  Norikra::Querydump::Format.text2json(src)
when 'json'
  Norikra::Querydump::Format.json2text(src)
else
  usage(1)
end
